### PR TITLE
Merging my fork repo back

### PR DESCRIPTION
**Pull request by tanapoln**
This PR is pick all new features that I implemented in my fork.

After this PR is merged, my fork repo will be archive along with a package released on NPM.

### Features added

There are 3 new features added which my company is using in development team right now.

#### 1. Arrow function without explicit return statement
Usually, the team wrote component with short style syntax, for example:

```jsx
const componentName = () => <div>
  <h1>Hello world</h1>
</div>;
```

With this PR, it support this style so the result will be:

```jsx
const componentName = () => <div data-qa="component-name">
  <h1>Hello world</h1>
</div>;
```

#### 2. Standard JS function as react component
React also support a normal JS function as component in JSX, the team also use this style sometimes.

```jsx
function SubComponent() {
  return <div>Sub</div>;
}
```

Then the plugin will produce this:

```jsx
function SubComponent() {
  return <div data-qa="sub-component">Sub</div>;
}
```

#### 3. Don't add data-qa for React's Fragment 
We also use Fragment but I found that it doesn't make sense to add data-qa to `Fragment` due to the result of DOM is not contains a `Fragment`, so we skip data-qa in this type of component.

### CODE REVIEW

**Comment by kevintyll** [comment]
Is there any plan to merge this PR in?  I'm also encountering an error that this PR fixes. I have a non-react class that throws an error in the `ArrowFunctionExpression`.  `if (!returnStatement) return;` eliminates the error.

Sample class:
```javascript
export default class Feature {
    constructor({ featureIdentifier }) {
        this._identifier = featureIdentifier;
        // more properties
    }
}
```

**Comment by tanapoln** [comment]
@davesnx This is weeks ago, I'll merge by myself.

**Comment by kevintyll** [comment]
Awesome.  Thanks.

**Pull request merged**
